import imagem1 from "../../public/Imagens/Img1-topico.jpg"
import imagem2 from "../../public/Imagens/Img2-topico.jpg"
import imagem3 from "../../public/Imagens/Img3-topico.jpg"

export default function Topicos(){
    return(
        <>
            <h1 className="text-3xl text-center text-[#44D764] py-6 font-bold">Fazendas de ventos para uma proteção a natureza</h1>
            <img className="h-[300px] w-full object-fit" src={imagem1} />
            <p className="mx-5 text-center py-6">Em uma era marcada por desafios climáticos sem precedentes, uma nova solução vem ganhando força e transformando paisagens ao redor do mundo: as fazendas de ventos. Essas gigantescas estruturas de turbinas eólicas, antes vistas apenas como geradoras de energia limpa, agora estão sendo reconhecidas como verdadeiros aliados na proteção da natureza e no combate às mudanças climáticas. Localizadas estrategicamente em áreas costeiras e planícies ventosas, as fazendas de ventos não apenas captam a força dos ventos para gerar eletricidade sustentável, mas também criam um impacto positivo no meio ambiente ao redor. Estudos recentes indicam que as regiões próximas às turbinas eólicas apresentam um aumento significativo na biodiversidade, com espécies de aves e pequenos mamíferos encontrando refúgio seguro entre as áreas protegidas pelas torres. Além disso, as fazendas de ventos desempenham um papel crucial na redução das emissões de gases de efeito estufa. Segundo especialistas, uma única fazenda pode evitar a liberação de milhões de toneladas de dióxido de carbono na atmosfera ao longo de sua vida útil, substituindo a necessidade de fontes de energia baseadas em combustíveis fósseis. “Essas estruturas são mais do que apenas geradores de energia limpa. Elas se tornaram um símbolo de resiliência ambiental e compromisso com o futuro do planeta,” destacou a ecologista Ana Beatriz Campos, que lidera um projeto de monitoramento da fauna em torno das fazendas eólicas. A expansão desse modelo de geração de energia enfrenta desafios, como a necessidade de mitigar possíveis impactos em rotas migratórias de aves e reduzir o ruído gerado pelas turbinas. No entanto, avanços tecnológicos têm garantido turbinas mais silenciosas e sensores que desativam as pás em caso de aproximação de aves. Com o crescimento das fazendas de ventos, governos e organizações ambientais enxergam uma oportunidade única de aliar progresso tecnológico e preservação da natureza. Em uma época em que o planeta clama por ações imediatas, essas gigantes do vento sopram esperança para um futuro mais sustentável.</p>

            <h1 className="text-3xl text-center text-[#44D764] py-6 font-bold">Aquecimento global se torna cada vez mais realidade</h1>
            <img className="h-[300px] w-full object-fit" src={imagem2} />
            <p className="mx-5 text-center py-6">O aquecimento global, antes considerado um alerta distante, se tornou uma realidade cada vez mais presente. Com temperaturas recordes, degelo acelerado nas regiões polares e eventos climáticos extremos, os impactos das mudanças climáticas já afetam milhões de pessoas ao redor do mundo. Pesquisas recentes mostram que, em 2024, a temperatura média global atingiu níveis inéditos, aproximando o planeta de um ponto crítico. O aumento no nível dos oceanos ameaça cidades costeiras, enquanto secas severas e ondas de calor comprometem a produção de alimentos e a disponibilidade de água. Especialistas alertam que a redução imediata das emissões de gases de efeito estufa é essencial para evitar consequências ainda mais catastróficas. “Não estamos falando mais de um futuro distante, mas de algo que já está moldando nosso presente”, destaca o climatologista Rafael Mendes. Embora ações globais estejam em curso, como a transição para energias renováveis, o ritmo atual ainda é insuficiente para conter o avanço das mudanças climáticas. A sociedade enfrenta um desafio urgente: unir esforços para preservar o planeta antes que os efeitos do aquecimento global se tornem irreversíveis.</p>

            <h1 className="text-3xl text-center text-[#44D764] py-6 font-bold">Condição dos ares se tornam cada vez piores</h1>
            <img className="h-[300px] w-full object-fit" src={imagem3} />
            <p className="mx-5 text-center py-6">A qualidade do ar ao redor do mundo está se deteriorando rapidamente, trazendo graves impactos à saúde humana e ao meio ambiente. O aumento das emissões industriais, o tráfego intenso e a queima de combustíveis fósseis são os principais responsáveis pelo crescimento alarmante da poluição atmosférica. Relatórios recentes apontam que grandes cidades enfrentam níveis de poluição muito acima do recomendado pela Organização Mundial da Saúde (OMS), levando a um aumento de problemas respiratórios e cardiovasculares.  “Estamos vendo o ar que respiramos se tornar uma ameaça invisível, especialmente para crianças e idosos”, alerta a ambientalista Carla Souza. Embora esforços como o incentivo ao transporte sustentável e a transição para energias limpas estejam em andamento, especialistas afirmam que mudanças mais rápidas e abrangentes são essenciais para conter a crise e garantir um futuro mais saudável para todos.</p>
        </>
    )
}